### ISSUE TITLE
Translate error .

### ISSUE THREAD

**Issue by DogancanYr** [anonymousException/renpy-translator#12]
Incompatible for GoodbyeEternity game.

**Comment by anonymousException** [comment]
Detail information , the output log?

**Comment by anonymousException** [comment]
And you can see the renpy in game folder is modified to support encryption
especially in renpy/loader.py , you can compare the difference between the orginal version and current one : 
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/403de1e9-5925-4325-a7b6-5792d14136d7)
Obviously there remains the decrypt  function , if you pay enough attention to explore this , it's not hard to decrypt
However I will not do this for you , it's not respectful for the orignal author , I explain this just for sturdy
You'd better obtain authorization from the original author who can offer you the unpacked game

**Comment by anonymousException** [comment]
Inspired by you, the new version supports the unpacking function and can support most encrypted games.
Just for study , you can try [v1.9.5](https://github.com/anonymousException/renpy-translator/releases/tag/v1.9.5)

https://github.com/anonymousException/renpy-translator/assets/157234942/25c64e79-7be1-4618-b3a2-c555f78db7fe

**Comment by anonymousException** [comment]
> 🥲🥲🥲 ![resim](https://private-user-images.githubusercontent.com/90002969/317476686-f8234d01-a9a3-4e02-bea3-8e856414f655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1ODcyNTMsIm5iZiI6MTcxMTU4Njk1MywicGF0aCI6Ii85MDAwMjk2OS8zMTc0NzY2ODYtZjgyMzRkMDEtYTlhMy00ZTAyLWJlYTMtOGU4NTY0MTRmNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAwNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNDRiMWJmMmU5ZDBmM2Q1Nzk0YjlkODgxYjlmY2JjNzJjNTYyMjBiYjJlZjU2ODllZmRlODUxYjE0YTlkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PR7l9dXHrUOoDyNWzNlKTyeq9LdL7NQ2yVZm38ZDXnI)

Try [v1.9.6](https://github.com/anonymousException/renpy-translator/releases/tag/v1.9.6)

**Comment by DogancanYr** [comment]
I guess the software doesn't support the game.
![resim](https://github.com/anonymousException/renpy-translator/assets/90002969/fab66ad9-a3b1-415f-89ee-1a9ad0c922fd)

**Comment by DogancanYr** [comment]
[nvapi-dummy.log](https://github.com/anonymousException/renpy-translator/files/14793364/nvapi-dummy.log)
[log.txt](https://github.com/anonymousException/renpy-translator/files/14793366/log.txt)

**Comment by anonymousException** [comment]
Unzip [expand.zip](https://github.com/anonymousException/renpy-translator/files/14800266/expand.zip) to game folder
And Try it again ,I presume your system is a streamlined version

**Comment by DogancanYr** [comment]
Ok, this is fixed, but when I select the whole game from the directory section, it does not respond, can something be done about it?

**Comment by anonymousException** [comment]
> Refer

You should wait until the game has already been unpacked , it's necessary
