### ISSUE TITLE
'MyMainForm' object has no attribute 'customEngineSettings'

### ISSUE THREAD

**Issue by maincq** [anonymousException/renpy-translator#13]
尝试通过源代码启动程序，遇到错误：
  ``` python
  'MyMainForm' object has no attribute 'customEngineSettings'
    File "D:\System\Download\renpy-translator-main\src\main.py", line 242, in __init__
      self.customEngineSettings.triggered.connect(lambda: self.show_custom_engine_settings())
      ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\System\Download\renpy-translator-main\src\main.py", line 576, in <module>
      myWin = MyMainForm()
              ^^^^^^^^^^^^
  AttributeError: 'MyMainForm' object has no attribute 'customEngineSettings'

**Comment by anonymousException** [comment]
> 尝试通过源代码启动程序，遇到错误：
> 
> ```python
> 'MyMainForm' object has no attribute 'customEngineSettings'
>   File "D:\System\Download\renpy-translator-main\src\main.py", line 242, in __init__
>     self.customEngineSettings.triggered.connect(lambda: self.show_custom_engine_settings())
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\System\Download\renpy-translator-main\src\main.py", line 576, in <module>
>     myWin = MyMainForm()
>             ^^^^^^^^^^^^
> AttributeError: 'MyMainForm' object has no attribute 'customEngineSettings'
> ```

当前最新的 main 还在开发中，最新版 v1.8.1 对应的提交节点是 db163e9c889799d49459af1bee3b3876b9396806
你可以切换到这个 commit

**Comment by maincq** [comment]
1.8.1可以正常启动
