### ISSUE TITLE
翻译错误怎么办

### ISSUE THREAD

**Issue by tianqinga** [anonymousException/renpy-translator#15]
部分翻译出来的文本与原文一样，需要重新翻译一遍吗

**Comment by anonymousException** [comment]
> 部分翻译出来的文本与原文一样，需要重新翻译一遍吗

这些文本是不是带有特殊符号比如 {} [] 等
有的时候翻译引擎无法很好地处理这些文本，你可能需要手动处理这些文本

**Comment by tianqinga** [comment]
确实是带了特殊符号的，数量还是很多的，这些只能手动翻译了吗

**Comment by anonymousException** [comment]
> 确实是带了特殊符号的，数量还是很多的，这些只能手动翻译了吗

Google 翻译对这种特殊符号比较友好，可以改用 Google 对这些处理后，如果还有残留的话只能手动翻译了
