### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by wwuuiitt** [anonymousException/renpy-translator#17]

**Comment by anonymousException** [comment]
Sorry for this late reply due to support one key translate
I will try to support in later version

**Comment by wwuuiitt** [comment]
Okay, thank you very much.
In fact, this function has been made by an author.
His code is open source.
But his software is too difficult to use.
You can learn from it when you are free.
Here is his github.
https://github.com/asonnychen/projz_renpy_translation/

**Comment by anonymousException** [comment]
> Okay, thank you very much. In fact, this function has been made by an author. His code is open source. But his software is too difficult to use. You can learn from it when you are free. Here is his github. https://github.com/asonnychen/projz_renpy_translation/

Why do not use the translation api ? there are plenty of translation engines to choose

**Comment by wwuuiitt** [comment]
The api is limited, and the translation of web pages is unlimited.

**Comment by anonymousException** [comment]
> The api is limited, and the translation of web pages is unlimited.

Actually the translation of web pages is also limited , the length of input is also limited
Besides it's not convenient, you have to copy the translated contents back to file and re-import it

**Comment by wwuuiitt** [comment]
I'll show you that the github author has realized the import of html format back to rpy. Some APIs need magic, but I'm not a person who often uses magic, and this is a demonstration video link of the software, so you can have a look.
https://b23.tv/qjRRl9k

**Comment by anonymousException** [comment]
> I'll show you that the github author has realized the import of html format back to rpy. Some APIs need magic, but I'm not a person who often uses magic, and this is a demonstration video link of the software, so you can have a look. https://b23.tv/qjRRl9k

It just acts as I mentioned : 
1. export to html 
2. use brower to open html file
3. call brower to translate
4. save translated contents overwrite
5. re-import

**Comment by wwuuiitt** [comment]
In fact, every translation software has its own characteristics.
Your software extraction function is better, and the extraction translation is more complete.
It's not bad for other authors to convert rpy to html.
In a word, it is very good that translation software can be used together.

**Comment by wwuuiitt** [comment]
Thank you for answering the question. Well, that's all for this chat.
This chat is just as a suggestion. I hope your renpy translation software will get better and better.
Before that, by the way, delete the conversation between us. I don't want to leave any traces on the Internet. Thank you.

**Comment by wwuuiitt** [comment]
> _No description provided._

**Comment by wwuuiitt** [comment]
Thank you for answering the question. Well, that's all for this chat.
This chat is just as a suggestion. I hope your renpy translation software will get better and better.
Before that, by the way, delete the conversation between us. I don't want to leave any traces on the Internet. Thank you.

**Comment by anonymousException** [comment]
> Thank you for answering the question. Well, that's all for this chat. This chat is just as a suggestion. I hope your renpy translation software will get better and better. Before that, by the way, delete the conversation between us. I don't want to leave any traces on the Internet. Thank you.

I will update the function in future version , just be patient

**Comment by anonymousException** [comment]
It's supportable now in [v2.0.7](https://github.com/anonymousException/renpy-translator/releases/tag/v2.0.7)
