### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wuit123** [anonymousException/renpy-translator#19]
When converting to html, there are no hidden variables, which leads to incorrect translation of web pages.

**Comment by anonymousException** [comment]
Do you mean replace special symbols ? like Hello [name] to Hello [0]

**Comment by wuit123** [comment]
Yes [] {}

**Comment by wuit123** [comment]
Yes [name] {}

**Comment by wuit123** [comment]
Yes, something like this.
[name] testing {b}it{/b} for two years,

**Comment by anonymousException** [comment]
It's supportable now , in [v2.0.8](https://github.com/anonymousException/renpy-translator/releases/tag/v2.0.8)

**Comment by wuit123** [comment]
I used other translation software to export the translation file txt.
That is, plain text format.
Then change the suffix to rpy.
Your software can't recognize it either.
Txt content typesetting is roughly as follows.

hope can recognize such typesetting txt and convert it into html.
There is no need to replace special characters.

Finally, turn html function into an interface separately.
Do not put it in [edit from rpy]
Xlsx is the same.
thank you

**Comment by wuit123** [comment]
![Uploading Image_1712466419984.jpg…]()

**Comment by wuit123** [comment]
Picture link
https://www.123pan.com/s/uVI0Vv-YMUud.html

**Comment by wuit123** [comment]
The typesetting content is as shown in the figure. Here is the picture link.
https://www.123pan.com/s/uVI0Vv-YMUud.html

**Comment by wuit123** [comment]
The typesetting content is as shown in the figure. Here is the picture link.
https://www.123pan.com/s/uVI0Vv-sMUud.html
