### ISSUE TITLE
point out

### ISSUE THREAD

**Issue by wuit123** [anonymousException/renpy-translator#21]
Your software returns special characters. There are still some problems.
I don't want you to solve it.
Because I intend to use it with other software.
I hope your software can help me put
Txt can be converted to html.

Keep the format of txt content when converting.
Don't leave a blank line.
The format of the content is like this.
Below is the content format reference link.
https://www.123pan.com/s/uVI0Vv-sMUud.html

Finally, turn html function into an interface.
Do not put it in /[edit from rpy/].
The same is true for xlsx.
thank you

**Comment by anonymousException** [comment]
Supported in [latest](https://github.com/anonymousException/renpy-translator/releases/latest)

**Comment by wuit123** [comment]
All right, very good
