### ISSUE TITLE
No-need-to-translate pattern

### ISSUE THREAD

**Issue by YauHsien** [anonymousException/renpy-translator#23]
I got a case of no-need-to-translate pattern: plain dots. Google translate engine will leave empty result as its "translation." 
![image](https://github.com/anonymousException/renpy-translator/assets/595388/da96925e-1f66-4105-901e-99dc694cb06a)

**Comment by anonymousException** [comment]
Got it , I will add a checkbox to skip translate the length of the untranslated contents (does not cotain special symbols) below xxx like the function in extraction
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/c482ecee-342a-4bd9-af87-4ae925983844)

**Comment by anonymousException** [comment]
Supported in [v2.1.8](https://github.com/anonymousException/renpy-translator/releases/tag/v2.1.8)
