### ISSUE TITLE
rpy文件编辑器无法导入精修好的内容

### ISSUE THREAD

**Issue by Hastur19** [anonymousException/renpy-translator#26]
我的步骤：
1、左下方rpy文件列表右键导出html（替换特殊符号）和xlsx文件，精修xlsx”当前的“列
2、左下方rpy文件列表右键”导入html和相关翻译内容“，选择未修改的html文件，以及从xlsx复制内容的txt文本，点击”导入文件“软件无反应

**版本**
2.2.3

还望大神解惑，谢谢~

**Comment by anonymousException** [comment]
能录个视频吗，我这里测试没问题

https://github.com/anonymousException/renpy-translator/assets/157234942/b41245f9-c51f-4e38-9266-b2547bcad076

**Comment by anonymousException** [comment]
确保导出来的内容在处理后每行都能对应上

**Comment by Hastur19** [comment]
仔细研究了好几遍大佬您的视频，终于找到了问题。

我导出的html一片空白，原因是“当前的"那一列是空白的。

”原来“列和”当前“列必须都有内容，要通过导出导入来翻译的内容其实是”当前的“那一列。具体到rpy文件里就是下图这样：
![rpy内容](https://github.com/anonymousException/renpy-translator/assets/168088674/fb7156ea-0876-491d-a803-aa636573b183)
后续就如老大视频里那样，导入html和复制翻译内容的txt，就基本完成了

大佬，我想提个建议，可不可以如同你视频里那样复制N行翻译内容后，直接粘贴到软件的已翻译里，就不用再导入了

**Comment by anonymousException** [comment]
导入是必要的，因为导入的前提是要有对应的导出数据的 html 文件
现在的导入已经很方便地自动填入上一次导出的 html 文件路径
直接粘贴的话无法确定导出的 html 文件，容易混淆
