### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by DogancanYr** [anonymousException/renpy-translator#27]
I'm trying to run the software for the Selene Apoptosis game but I can't, the game gives me an error every time. It should work, logically.

**Comment by anonymousException** [comment]
Any detail information? I test the game but it work well
What's the error and when it occurs?

**Comment by DogancanYr** [comment]
Can you tell me the steps you did?
I think I did something wrong.

**Comment by DogancanYr** [comment]
Since software doesn't translate every sentence, I didn't understand that the software works.

**Comment by anonymousException** [comment]
> Since software doesn't translate every sentence, I didn't understand that the software works.

Not all sentences can be extracted by the software , it depends on the code developed by the original author
If the code is not friendly enough to extract or translate , some sentences may miss the translation
