### ISSUE TITLE
大佬，可以添加一个自动保存目标语言设置吗？

### ISSUE THREAD

**Issue by 994834669** [anonymousException/renpy-translator#28]
每次打开翻译器就得重新设置一次源语言和目标语言，在跑openai翻译接口的时候老是忘记调整目标语言，浪费了很多时间，可以添加一个自动保存上次翻译完成的设置吗？

**Comment by 994834669** [comment]
但这也是因为我的粗心导致的，不过大佬能添加这个功能就更好了。

**Comment by anonymousException** [comment]
已在 [v2.3.8](https://github.com/anonymousException/renpy-translator/releases/tag/v2.3.8) 支持
