### ISSUE TITLE
有一个问题，tl目录中子文件夹过多就不翻译了。

### ISSUE THREAD

**Issue by 1666059026** [anonymousException/renpy-translator#31]
DEEP_VAULT_69-0.3.9-pc\game\tl\chinese\g_script\core\events\side_quest\aska_quest

![image](https://github.com/anonymousException/renpy-translator/assets/75952126/0754da1b-e513-48c1-86fc-364b6c687822)
子文件夹过深就不翻译了，我使用的是目前程序的翻译---当前---

[english.zip](https://github.com/user-attachments/files/16039704/english.zip)
![image](https://github.com/anonymousException/renpy-translator/assets/75952126/03b75840-30df-457a-ab0b-9eb0838049a9)
而且还有一个问题就是漏翻有点多，我怀疑是多线程翻译的问题，但是我取消了这个，仍然会出现漏翻，某些文件几百行就翻译就一行。

我看了一下是正常对话。希望能检查修复一下

**Comment by anonymousException** [comment]
我这里测试没有这个问题，这些文件夹都看了
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/3b59ba54-8479-4e96-90b9-4fa7d9c1dac8)

![image](https://github.com/anonymousException/renpy-translator/assets/157234942/34b4c3a6-71ba-4dfe-96b4-d8fd179e3962)

**Comment by anonymousException** [comment]
不要勾选 跳过翻译(原始!=当前)，我看了你的源文件， old 和 new 不一样，被认为是翻译过的，所以跳过了翻译
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/6fa2b8a2-5b0a-4e48-a864-2488b4e5a25a)
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/676dad2d-5829-4336-8c0e-3ab374c9de25)

**Comment by 1666059026** [comment]
OK，我在看看

**Comment by 1666059026** [comment]
![image](https://github.com/user-attachments/assets/16750f16-be43-491e-9637-71764c0d9b9c)

这些单独行的目前软件不兼容，无法翻译，可以尝试兼容吗？

还挺多这种的。
[english.zip](https://github.com/user-attachments/files/16561572/english.zip)

**Comment by anonymousException** [comment]
> ![image](https://private-user-images.githubusercontent.com/75952126/356602964-16750f16-be43-491e-9637-71764c0d9b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjU0ODMsIm5iZiI6MTcyNDEyNTE4MywicGF0aCI6Ii83NTk1MjEyNi8zNTY2MDI5NjQtMTY3NTBmMTYtYmU0My00OTFlLTk2MzctNzE3NjRjMGQ5YjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAzMzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODgwNDRjMWUwYTFjMGIzOWYxY2Q4YzE4ODdlN2FhMTIzMjRkNjE0Njc2OTY0NzhkOWUyNzIwMmQxODE0NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1qXoO3eFlpw3KI70yt9PfYwmgUkiPfb-ox44szwmqI)
> 
> 这些单独行的目前软件不兼容，无法翻译，可以尝试兼容吗？
> 
> 还挺多这种的。 [english.zip](https://github.com/user-attachments/files/16561572/english.zip)
试试这个格式化，先格式化一下，这样就支持翻译了

https://github.com/user-attachments/assets/bef24a4a-0d1c-4cfa-9f22-fdafba731c1f
