### ISSUE TITLE
大佬，游戏使用控制台reload报错

### ISSUE THREAD

**Issue by githubli50** [anonymousException/renpy-translator#35]
[traceback.txt](https://github.com/user-attachments/files/16366315/traceback.txt)

**Comment by 1666059026** [comment]
tl/pingcn/gui.rpy

把这个路径的文件删了

**Comment by 1666059026** [comment]
在game-gui-把字体改成你需要的字体，我看这个问题好像在新版本修复了，你可以重新翻译试一下

**Comment by anonymousException** [comment]
已在新版本修复，删除 gui.rpy 和 gui.rpyc ， 然后重新使用替换字体功能即可
