### ISSUE TITLE
请求兼容，文本无法提取。

### ISSUE THREAD

**Issue by 1666059026** [anonymousException/renpy-translator#36]
软件版本：2.4.4

问题如下：
![image](https://github.com/user-attachments/assets/b405c980-ab0c-4ec1-8fe2-15a486355187)

在PMC Promiscuity这个游戏中，使用官方，或者软件自带的抽取，均无法抽取语音行对应的文本，只能提取到语音行。

下载链接：https://mega.nz/file/VuMFxK7C#wC6MPXvl0DOsvNv5_KeNVCJXzCAP9S1IQbCW-K_P4Js

**Comment by anonymousException** [comment]
重复的文本不会被反复提取，你会发现在 OldContent.rpy 里已经提取过了，实际上是有正常抽取的
![QQ_1722479350722](https://github.com/user-attachments/assets/7e1bf3d4-e8c8-4b37-b095-fcc3e8f27611)
