### ISSUE TITLE
Translate not in order in one key translate

### ISSUE THREAD

**Issue by JoeLurmel** [anonymousException/renpy-translator#39]
Hi,
When using runtime extraction in one key translate, all script files in not in sequential order, except the mandatory renpy files. Can it be solved ?

**Comment by anonymousException** [comment]
I‘ll try to improve this in later version

**Comment by ML72-0** [comment]
This problem still occurs, especially when using DeepL for translations.

**Comment by JoeLurmel** [comment]
I’m using Google

 

De : ML72-0 ***@***.***> 
Envoyé : vendredi 3 janvier 2025 17:46
À : anonymousException/renpy-translator ***@***.***>
Cc : JoeLurmel ***@***.***>; Author ***@***.***>
Objet : Re: [anonymousException/renpy-translator] Translate not in order in one key translate (Issue #39)

 

This problem still occurs, especially when using DeepL for translations.
