### ISSUE TITLE
. Bug

### ISSUE THREAD

**Issue by jusaozzz** [anonymousException/renpy-translator#4]
Hey unlimited folders with the same name. No, he doesn't work. I think it should be a bug

2024-02-18 3:27:12	Traceback (most recent call last):
  File "main.py", line 287, in extract
  File "renpy_extract.py", line 395, in ExtractAllFilesInDir
  File "renpy_extract.py", line 267, in CreateEmptyFileIfNotExsit
  File "os.py", line 418, in _walk
  File "os.py", line 418, in _walk
  File "os.py", line 418, in _walk
  [Previous line repeated 989 more times]
  File "os.py", line 412, in _walk
  File "ntpath.py", line 90, in join
  File "ntpath.py", line 143, in splitdrive
RecursionError: maximum recursion depth exceeded while calling a Python object

![Screenshot_269](https://github.com/anonymousException/renpy-translator/assets/155393679/090b5349-3f80-4a5c-91a8-c264ae8a6977)

**Comment by anonymousException** [comment]
Can you offer the folder path which causes the error?

**Comment by jusaozzz** [comment]
\MILFLAB-patreon0.35-pc\MagicalFamilyLaboratory-pc\game\RC\RC

**Comment by jusaozzz** [comment]
The extraction is all 0kb and has the same name infinitely.

**Comment by jusaozzz** [comment]
Before loading the script.
FileNotFoundError: [WinError 3] 
\\MILFLAB-patreon0.35-pc\\MagicalFamilyLaboratory-pc\\game/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC/RC'

**Comment by anonymousException** [comment]
Are you using the latest version v1.4.5? I do not meet the problem with double same folder name.
Maybe I need to download the game you mentioned : MagicalFamilyLaboratory ?

**Comment by jusaozzz** [comment]
D'accord, je vais vous donner le résultat.

**Comment by jusaozzz** [comment]
J'ai téléchargé cette dernière version correctement et cela montre qu'elle peut être résolue normalement. Mais pourquoi ne peut-il pas être extrait.Le fichier en RC? Pourquoi dois-je être le fichier tl par défaut pour l'extraire?

**Comment by anonymousException** [comment]
> J'ai téléchargé cette dernière version correctement et cela montre qu'elle peut être résolue normalement. Mais pourquoi ne peut-il pas être extrait.Le fichier en RC? Pourquoi dois-je être le fichier tl par défaut pour l'extraire?
The files under RC folder is already extracted , you can found the extracted files under tl/RC/RC
The reason why you have to input the tl folder is that ren'py engine use tl folder to make translation do effect
So extraction result is generated to tl folder

**Comment by jusaozzz** [comment]
Merci pour votre réponse. Ou existe-t-il un moyen d'extraire des fichiers non tl? Merci.

**Comment by jusaozzz** [comment]
Y a-t-il un moyen d'éviter cette situation? Je pense que si vous pouviez arrêter de maintenir le projet plus tard. Personne ne continuera à l'entretenir. Alors comment éviter ce genre de situation

**Comment by anonymousException** [comment]
The extract result should always be generated to tl folder
But mult-files extraction is also supported , you can extract files like this :
https://github.com/anonymousException/renpy-translator/assets/157234942/ed65c94d-27e4-4bd7-81f8-6566ea109e0e

**Comment by jusaozzz** [comment]
Okay, I see. You mean tl needs 1 name and then extracts it to tl?

**Comment by jusaozzz** [comment]
Very well, he successfully solved it. As I mentioned, how to avoid this situation Main py if this project is not maintained by anyone.

**Comment by anonymousException** [comment]
> Okay, I see. You mean tl needs 1 name and then extracts it to tl?

Yes , tl is needed when extraction

**Comment by anonymousException** [comment]
> Very well, he successfully solved it. As I mentioned, how to avoid this situation Main py if this project is not maintained by anyone.

No need to worried about nobody maintained , I will maintain this project until is keeps stable enough
I'm still improving the document and the tool

**Comment by anonymousException** [comment]
If there remains no other problem. Please close the issue.
Thanks to your issue , I improve the document with the new usage video : extract file(s) , you can found it on https://github.com/anonymousException/renpy-translator#usage

**Comment by jusaozzz** [comment]
.bye
