### ISSUE TITLE
“将翻译源翻译到翻译后的内容”会出现错误

### ISSUE THREAD

**Issue by FThePatriarchy** [anonymousException/renpy-translator#41]
v2.4.5。使用高级选项中的编辑rpy时，大批量（几千条）使用“将翻译源翻译到翻译后的内容”时，出现翻译错误。少量（几十条）使用不会出现错误
![image](https://github.com/user-attachments/assets/dc5bdc72-750a-498a-9e0d-4e44dfa150b9)

使用ai翻译到excel后，想要导入到rpy中
导入excel没有问题
但是，大量使用“将翻译源翻译到翻译后的内容”时，总是翻译不对文本

附件是ai翻译的excel，以及拆包中文机翻，游戏为SunshineLoveCH2
非常感谢！
[ch2.xlsx](https://github.com/user-atta
[chinese.zip](https://github.com/user-attachments/files/16647931/chinese.zip)
chments/files/16647921/ch2.xlsx)
![image](https://github.com/user-attachments/assets/e75e40b2-40e5-4528-b31e-d5f6aaace5de)

**Comment by anonymousException** [comment]
表格文件下载不到，再确认下，只有 AI 翻译会出现这个乱序问题？

**Comment by FThePatriarchy** [comment]
[ch2.xlsx](https://github.com/user-attachments/files/16655490/ch2.xlsx)
又发了一遍，不知道可以不可以
我是之前用的这个项目ai翻译https://github.com/jxq1997216/AITranslator，然后输出了一个excel文件。暂时还没有用过renpy-translator 的ai功能。也还没有自己翻译的表格文件
[log.txt](https://github.com/user-attachments/files/16655503/log.txt)

**Comment by anonymousException** [comment]
用法错了，xlsx 是用于本地词库替换指定单词的，比如：把 Elieen 替换为 艾琳
外部翻译应该导出为 html , 然后再导入对应翻译后的文本，注意文本顺序必须一一对应，不能有空行
例子：

https://github.com/user-attachments/assets/6e48eb8e-53f2-4e49-9df4-9c9572684033

**Comment by FThePatriarchy** [comment]
谢谢澄清！之前根据这个教程来的
https://docs.dclef.icu/util/renpy-translator.html#_5-%E6%B7%BB%E5%8A%A0%E8%AF%AD%E8%A8%80%E5%85%A5%E5%8F%A3
再次感谢详细解释和例子！
