### ISSUE TITLE
请问大佬，软件支持自定义openai的系统提示词吗？

### ISSUE THREAD

**Issue by 2776108571** [anonymousException/renpy-translator#42]
**Is your feature request related to a problem? Please describe.**
大佬您好
我目前使用您的软件，感觉非常好用！
但是也遇到了一点小问题

因为我是部署本地中英文模型然后用openai的接口进行翻译
因此并没有GPT那么好的效果，需要更细致的提示词的描述
我对于自己使用的这款模型翻译提示词的撰写颇有心得
所以想问问大佬

**Describe the solution you'd like**
软件是否支持自定义提示词和参数

**Describe alternatives you've considered**
或者在哪个文件可以修改系统提示词参数

**Additional context**
感谢大佬开源软件，希望能得到您的回复！

**Comment by anonymousException** [comment]
暂时不支持自定义，等我后面的版本支持下

**Comment by 2776108571** [comment]
好的，感谢大佬

**Comment by anonymousException** [comment]
已在最新版本支持，注意要保留 3 个参数 :

**Comment by 2776108571** [comment]
感谢大佬进行更新
