### ISSUE TITLE
Renpy game

### ISSUE THREAD

**Issue by huseyin0072** [anonymousException/renpy-translator#43]
first of all thanks for making this wonderful programme.

My request is this; in some renpy games the task list part is not translated. the only key is in the translation, everything else is perfect

**Comment by anonymousException** [comment]
Can you list the detail games, I need to figure out the relative code to find the reason

**Comment by huseyin0072** [comment]
Thank you very much. I will list the games I know;

Mist f95: https://f95zone.to/threads/mist-v1-0-3-395games.42509/
Desert Stalker f95: https://f95zone.to/threads/desert-stalker-v0-16c-zetan.68105/
Milfy City f95: https://f95zone.to/threads/milfy-city-v1-0e-icstor.8012/
Deluca Family f95: https://f95zone.to/threads/the-deluca-family-season-1-hopesgaming.15459/

**Comment by anonymousException** [comment]
> Thank you very much. I will list the games I know;
> 
> Mist f95: https://f95zone.to/threads/mist-v1-0-3-395games.42509/ Desert Stalker f95: https://f95zone.to/threads/desert-stalker-v0-16c-zetan.68105/ Milfy City f95: https://f95zone.to/threads/milfy-city-v1-0e-icstor.8012/ Deluca Family f95: https://f95zone.to/threads/the-deluca-family-season-1-hopesgaming.15459/ Photo Hunt f95: https://f95zone.to/threads/photo-hunt-v0-16-3-extra-moochie.25264/ The Bum f95: https://f95zone.to/threads/the-bum-v0-8-0-beta-jtstudio.129476/ Midnight Paradise f95: https://f95zone.to/threads/midnight-paradise-v0-25-elite-lewdlab.25081/ My cute roommate f95: https://f95zone.to/threads/my-cute-roommate-2-v1-1-05280-extra-astaros3d.90002/

For Mist f95 (what I tested) you can untick the Enable filter for extract option
![image](https://github.com/user-attachments/assets/4ba87642-e881-4d40-804a-0a9a392d576e)

**Comment by huseyin0072** [comment]
did you put the dialogues in the tl folder first and then make the translation?

**Comment by anonymousException** [comment]
> did you put the dialogues in the tl folder first and then make the translation?你是先把对话放在tl文件夹里然后再翻译吗？

Just use the order of one key translate

**Comment by huseyin0072** [comment]
i turned the mist game. there were no problems. but when translating the midnight paradise game, I couldn't translate the election parts into Turkish

![Screenshot_2](https://github.com/user-attachments/assets/b872c3ab-7978-47f5-a253-3d46574fc8ef)

**Comment by anonymousException** [comment]
> i turned the mist game. there were no problems. but when translating the midnight paradise game, I couldn't translate the election parts into Turkish
> 
> ![Screenshot_2](https://private-user-images.githubusercontent.com/154922536/363415904-b872c3ab-7978-47f5-a253-3d46574fc8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjQ4NzMsIm5iZiI6MTcyNTE2NDU3MywicGF0aCI6Ii8xNTQ5MjI1MzYvMzYzNDE1OTA0LWI4NzJjM2FiLTc5NzgtNDdmNS1hMjUzLTNkNDY1NzRmYzhlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNDIyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjBjZDdhZGQ4OGQ3OGY0OThmOTg2ZDQ3N2QzZDAzZmY5MDNlMzcwNmYxZmZlOWIxNGEzYmM1M2U1YzgyZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ry8WaJjFBd9igD8laA9QEkSuUIiGxmdzWQhLDAK_swY)

In my test, it works well
![image](https://github.com/user-attachments/assets/2cb354fe-25e2-4ddd-91bb-8362de8bb8c8)

**Comment by huseyin0072** [comment]
please add translation tool for deepl pro
