### ISSUE TITLE
Deepl translator

### ISSUE THREAD

**Issue by huseyin0072** [anonymousException/renpy-translator#44]
first of all, hello, thank you for making this great program.

i have a deepl pro membership. but the only key is giving a deepl error in translation. it never translates, unfortunately

**Comment by anonymousException** [comment]
During my test, it still works well. The DEEL API is offered by the official service.
Are you sure you can access the url and do you input the correct key token?
    _DEEPL_SERVER_URL = "https://api.deepl.com"
    _DEEPL_SERVER_URL_FREE = "https://api-free.deepl.com"

**Comment by huseyin0072** [comment]
yes, I can't translate files with deepl pro

**Comment by anonymousException** [comment]
> yes, I can't translate files with deepl pro

Can you offer the log file?

**Comment by huseyin0072** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/d54ef193-122e-4213-b0d0-9f5c43badf08)
i'm entering the api key, but it's not working.

**Comment by anonymousException** [comment]
Try [v2.5.1](https://github.com/anonymousException/renpy-translator/releases/tag/v2.5.1) which upgrade the deepl api

**Comment by huseyin0072** [comment]
i'm getting this error;

ImportError: attempted relative import with no known parent package

**Comment by anonymousException** [comment]
> i'm getting this error;
> 
> ImportError: attempted relative import with no known parent package

If you are trying to write a custom api, you need to write import inside the function , otherwise will cause NameError
You can refer to the template [caiyun.py](https://github.com/anonymousException/renpy-translator/blob/main/src/custom_engine/caiyun.py) and [baidu.py](https://github.com/anonymousException/renpy-translator/blob/main/src/custom_engine/baidu.py) (the api name must be tranlate_single or tranlate_queue)

**Comment by huseyin0072** [comment]
i don't know how to import

**Comment by huseyin0072** [comment]
please help me to use deepl pro translation

**Comment by anonymousException** [comment]
> please help me to use deepl pro translation

It's weird,  during my test, it works well for free deepl api and it should work for pro version
The api is from the official website : https://developers.deepl.com/docs/getting-started/your-first-api-request

**Comment by anonymousException** [comment]
Do you have any request errors？
like 
Traceback (most recent call last):

  File "D:\PycharmProjects\renpy_translator\src\deepl_translate.py", line 53, in translate_limit

    result = self.translator.translate_text(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\deepl\translator.py", line 446, in translate_text

    self._raise_for_status(status, content, json)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\deepl\translator.py", line 183, in _raise_for_status

    raise AuthorizationException(

deepl.exceptions.AuthorizationException: Authorization failure, check auth_key

**Comment by huseyin0072** [comment]
i have no idea about the codes. please add deepl pro to the translation engines in the new version

**Comment by anonymousException** [comment]
> i have no idea about the codes. please add deepl pro to the translation engines in the new version

I try the deepl pro key, it works well
Can you access the following webite ? 
https://www.deepl.com/en/your-account/keys
![image](https://github.com/user-attachments/assets/0675d062-616a-4c34-9c2b-171a0e606d8e)
![image](https://github.com/user-attachments/assets/8e5a6e80-6331-47fa-a680-3858a8be47ed)

**Comment by huseyin0072** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/df6eeb15-a06d-4746-93d0-e84f72554a25)

**Comment by anonymousException** [comment]
> ![Screenshot_1](https://private-user-images.githubusercontent.com/154922536/365102520-df6eeb15-a06d-4746-93d0-e84f72554a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTM0ODQsIm5iZiI6MTcyNTYxMzE4NCwicGF0aCI6Ii8xNTQ5MjI1MzYvMzY1MTAyNTIwLWRmNmVlYjE1LWEwNmQtNDc0Ni05M2QwLWU4NGY3MjU1NGEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwODU5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzkxYjJlMDY2ODgxYjc4MzY2MWJmOWY5MzUxMzY2NDQ1ZjcyMmMwZTk3ZGFiZDhmOTY3MTczNjVjMjk4YTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G9QMLYnZtjx5UT_NUZarJXHZ6Dlhmx1BBFXIP2eZcy0)

It seems like that your key is invalid?  Try to get a new one

**Comment by huseyin0072** [comment]
he made the same mistake again. i guess I can't do it

**Comment by anonymousException** [comment]
> he made the same mistake again. i guess I can't do it

you may need  to ask deepl for help due to the account problem,  active deepl pro key is required
![image](https://github.com/user-attachments/assets/69579f2a-2325-444e-887e-04170dc34f57)

**Comment by huseyin0072** [comment]
the api keys part does not appear to me

**Comment by anonymousException** [comment]
> the api keys part does not appear to me

Try to create a new key?

**Comment by huseyin0072** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/a534905f-8cc3-48d9-80d0-ef63861b137c)
to me deepl.py can you send the file?

**Comment by anonymousException** [comment]
> ![Screenshot_2](https://private-user-images.githubusercontent.com/154922536/365124194-a534905f-8cc3-48d9-80d0-ef63861b137c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTg5MzcsIm5iZiI6MTcyNTYxODYzNywicGF0aCI6Ii8xNTQ5MjI1MzYvMzY1MTI0MTk0LWE1MzQ5MDVmLThjYzMtNDhkOS04MGQwLWVmNjM4NjFiMTM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMDMwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWIzNGExYWUwM2JmYjI1OGYyMjljYzI5YmQ0NWQ1MTFiZWEwYjk2ZTczOThjOGY0NWU4NWUwYzYxNGM0OWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTflFU84xwhUngBbLJQJTcJeHOYdpL3FW1ATLzqORRY) to me deepl.py can you send the file?

Maybe later, I am busy now, tomorrow

**Comment by huseyin0072** [comment]
ok bro

**Comment by anonymousException** [comment]
> ok bro
Try the pre test version
You can download it from https://github.com/anonymousException/renpy-translator/actions/runs/10748889698
https://github.com/anonymousException/renpy-translator/blob/main/src/custom_engine/deepl_custom.py
![image](https://github.com/user-attachments/assets/866bd92e-dd11-4175-9486-114df3c198c6)

**Comment by huseyin0072** [comment]
thank you, brother, the problem is solved)

**Comment by huseyin0072** [comment]
can you make an anime translation program like this? :)
