### ISSUE TITLE
I hope to extract more.Instead of repeated extraction.

### ISSUE THREAD

**Issue by jusaozzz** [anonymousException/renpy-translator#6]
I hope to extract more.Instead of repeated extraction.

Instead of repeated extraction. How to do it

**Comment by anonymousException** [comment]
Actually I don't get your point . What do you want for detail example ?

**Comment by anonymousException** [comment]
Repeated extraction would not happend in current version , For example , if the translation message already exists in tl folder
like : 
```python
old "Hello"
new "Translated Hello"
```
Then "Hello" will not be extracted again

**Comment by jusaozzz** [comment]
1.5.7?

**Comment by anonymousException** [comment]
> 1.5.7?

Actually in early version it has been supported , of course the version 1.5.7 is supported

**Comment by jusaozzz** [comment]
okay What new features are coming later? With regard to extraction.

**Comment by jusaozzz** [comment]
More comprehensive extraction.

**Comment by anonymousException** [comment]
> okay What new features are coming later? With regard to extraction.

actually the extraction is stable enough to use since [v1.4.4](https://github.com/anonymousException/renpy-translator/releases/tag/v1.4.4)

Later update is to fix some small bugs and support more translation engine like openai

**Comment by anonymousException** [comment]
> More comprehensive extraction.

The current extraction is comprehensive enough to use , most of string can be extracted
What do you wish to improve about the extraction function , I do not mind to listen more suggestion

**Comment by anonymousException** [comment]
I will update the issue to the document , I forget to explain the feature that extraction will auto skip the extracted contents , do not worry about repeat extraction
