### ISSUE TITLE
version

### ISSUE THREAD

**Issue by jusaozzz** [anonymousException/renpy-translator#8]
It's the duplication that's happening with the multi-folder extraction. If I remember correctly, it should be the latest version.

**Comment by anonymousException** [comment]
the issue mentioned before?

**Comment by anonymousException** [comment]
Is the directory you filled under tl folder?

**Comment by anonymousException** [comment]
I re-check the problem and extract files with multi-directory , everything goes well

**Comment by jusaozzz** [comment]
100 w directories Renaming N+ should be a bug Suggest you check it out

**Comment by anonymousException** [comment]
> 100 w directories Renaming N+ should be a bug Suggest you check it out

I need to repeat the error , how to operate to repeat the error?

**Comment by jusaozzz** [comment]
I forget what I said in the previous question, but I downloaded the latest version, which is the newest version, and after extracting it, I couldn't delete the folder, and there was nothing in the folder at 0 kilobytes. I think it's a bug.

**Comment by jusaozzz** [comment]
I think it's a bug. The extraction was successful, but the folder couldn't be deleted. I'm not sure if I'll see it again. Don't test it so easily. He can't be deleted. Rebooting won't help.

**Comment by anonymousException** [comment]
> I think it's a bug. The extraction was successful, but the folder couldn't be deleted. I'm not sure if I'll see it again. Don't test it so easily. He can't be deleted. Rebooting won't help.

It's pretty weird , I will try to fix it if you can tell me how to make it happened

**Comment by anonymousException** [comment]
And what you mentioned in pre issue , I think it is due to wrong directory input . I'll try to limit the directory folder length to avoid the problem

**Comment by anonymousException** [comment]
According to your issue , I review the relative extraction code , and improve the code in [v1.6.0](https://github.com/anonymousException/renpy-translator/releases/tag/v1.6.0)
You can try the version , perhaps the problem you mentioned is already fixed
